# Generated by Django 3.2 on 2021-05-12 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_agenda', models.CharField(max_length=60, verbose_name='Nombre')),
                ('lenguaje_programacion', models.CharField(max_length=60, verbose_name='Lenguaje programación')),
                ('fecha', models.DateTimeField(verbose_name='Fecha reunión')),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(default='Nombre Empresa', max_length=60, verbose_name='empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Entrevistado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, verbose_name='nombre')),
                ('apellido', models.CharField(max_length=60, verbose_name='apellido')),
                ('email', models.EmailField(max_length=128, verbose_name='direccion email')),
                ('contraseña', models.CharField(max_length=60, verbose_name='contraseña')),
            ],
        ),
        migrations.CreateModel(
            name='Reunion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('duracion', models.PositiveIntegerField()),
                ('link', models.URLField(default='ejemplo.com', max_length=280, verbose_name='link reunion')),
            ],
        ),
        migrations.CreateModel(
            name='Entrevistador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, verbose_name='nombre')),
                ('apellido', models.CharField(max_length=60, verbose_name='apellido')),
                ('rol', models.CharField(max_length=60, verbose_name='rol')),
                ('email', models.EmailField(max_length=128, verbose_name='direccion email')),
                ('contraseña', models.CharField(max_length=60, verbose_name='contrase単a')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='iterview.empresa')),
            ],
        ),
    ]
