# Generated by Django 3.2.4 on 2021-06-23 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iterview', '0002_auto_20210514_1552'),
        ('iterview', '0002_auto_20210526_1540'),
    ]

    operations = [
    ]
